### ISSUE TITLE
bug: 似乎API返回的接口有变化，无法正常预览和下载

### ISSUE THREAD

**Issue by Cinea4678** [tzwm/sd-webui-model-downloader-cn#13]
输出：
```
Traceback (most recent call last):
  File "/root/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "/root/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "/root/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/root/stable-diffusion-webui/venv/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/root/stable-diffusion-webui/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/root/stable-diffusion-webui/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/root/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "/root/stable-diffusion-webui/extensions/sd-webui-model-downloader-cn/scripts/model-downloader-cn.py", line 109, in preview
    return [f"预览成功{more_guides}"] + resp_to_components(resp) + \
  File "/root/stable-diffusion-webui/extensions/sd-webui-model-downloader-cn/scripts/model-downloader-cn.py", line 89, in resp_to_components
    resp["version"]["updatedAt"],
KeyError: 'updatedAt'
```

出现问题的链接：https://civitai.com/models/44907?modelVersionId=49883

**Comment by tzwm** [comment]
我最近找时间更新一下，感谢反馈

**Comment by tzwm** [comment]
civitai 做了限制，仅能登录用户访问下载接口了，我没法再做 proxy 了。

**Comment by Cinea4678** [comment]
明白，辛苦了～
