### ISSUE TITLE
证书过期怎么破

### ISSUE THREAD

**Issue by BursonHandsom** [tzwm/sd-webui-model-downloader-cn#4]
*** Error executing callback ui_tabs_callback for /root/autodl-tmp/stable-diffusion-webui/extensions/sd-webui-model-downloader-cn/scripts/model-downloader-cn.py
    Traceback (most recent call last):
      File "/root/miniconda3/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
        httplib_response = self._make_request(
      File "/root/miniconda3/lib/python3.10/site-packages/urllib3/connectionpool.py", line 386, in _make_request
        self._validate_conn(conn)
      File "/root/miniconda3/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
        conn.connect()
      File "/root/miniconda3/lib/python3.10/site-packages/urllib3/connection.py", line 414, in connect
        self.sock = ssl_wrap_socket(
      File "/root/miniconda3/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
        ssl_sock = _ssl_wrap_socket_impl(
      File "/root/miniconda3/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
        return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
      File "/root/miniconda3/lib/python3.10/ssl.py", line 513, in wrap_socket
        return self.sslsocket_class._create(
      File "/root/miniconda3/lib/python3.10/ssl.py", line 1071, in _create
        self.do_handshake()
      File "/root/miniconda3/lib/python3.10/ssl.py", line 1342, in do_handshake
        self._sslobj.do_handshake()
    ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/root/miniconda3/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
        resp = conn.urlopen(
      File "/root/miniconda3/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
        retries = retries.increment(
      File "/root/miniconda3/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
        raise MaxRetryError(_pool, url, error or ResponseError(cause))
    urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='raw.fastgit.org', port=443): Max retries exceeded with url: /tzwm/sd-webui-model-downloader-cn/main/docs/banner.md (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)')))

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/root/autodl-tmp/stable-diffusion-webui/modules/script_callbacks.py", line 153, in ui_tabs_callback
        res += c.callback() or []
      File "/root/autodl-tmp/stable-diffusion-webui/extensions/sd-webui-model-downloader-cn/scripts/model-downloader-cn.py", line 169, in on_ui_tabs
        banner, footer = request_online_docs()
      File "/root/autodl-tmp/stable-diffusion-webui/extensions/sd-webui-model-downloader-cn/scripts/model-downloader-cn.py", line 157, in request_online_docs
        res = requests.get(ONLINE_DOCS_URL + "banner.md")
      File "/root/miniconda3/lib/python3.10/site-packages/requests/api.py", line 73, in get
        return request("get", url, params=params, **kwargs)
      File "/root/miniconda3/lib/python3.10/site-packages/requests/api.py", line 59, in request
        return session.request(method=method, url=url, **kwargs)
      File "/root/miniconda3/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
        resp = self.send(prep, **send_kwargs)
      File "/root/miniconda3/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
        r = adapter.send(request, **kwargs)
      File "/root/miniconda3/lib/python3.10/site-packages/requests/adapters.py", line 517, in send
        raise SSLError(e, request=request)
    requests.exceptions.SSLError: HTTPSConnectionPool(host='raw.fastgit.org', port=443): Max retries exceeded with url: /tzwm/sd-webui-model-downloader-cn/main/docs/banner.md (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:9

**Comment by tzwm** [comment]
修好了，可以更新下插件。感谢反馈！
